### ISSUE TITLE
React and Next.js best practices

### ISSUE THREAD

**Issue by lucavallin** [lucavallin/verto#203]
We have done a good job at writing quality code, but it is important to always review the state of the codebase to improve it and update itL

- Are we following React's and Next.js best practices?
- Is our use of React and Next.js up-to-date?

This is an on-going "issue" that will remain open: do you see anything that could be improved? Let us know and feel free to open a pull request.

**Comment by Vivek-04022001** [comment]
I have notice one problem in index.tsx related to error handling 
Best Practice says: 
Error Handling: Ensure that you have proper error handling in case the repositories data is not available or there's an error while fetching it.

Here in this code , we should using the error handling 
![image](https://github.com/lucavallin/first-issue/assets/91373023/7b818416-e43f-4bba-8c91-e0013f823545)

**After**
```
export default function Home() {
  const { repositories } = useAppData();

  return (
    <>
      <Head>
        <title>First Issue | Issues for your next open-source contribution</title>
      </Head>
  👉    {repositories.length > 0 && <RepositoryList repositories={repositories} />}
    </>
  );
}

```

**Comment by lucavallin** [comment]
@Vivek-04022001 Thanks! I don't think this is particularly relevant for us given that the data is always hard-coded in the generated json file. I would instead make sure that the `RepositoryList` components doesn't break if there are no repos.

**Comment by Tabindanoor** [comment]
I would like to implement it..
