### ISSUE TITLE
Use SSR functions instead of reading json directly.

### ISSUE THREAD

**Issue by lucavallin** [lucavallin/verto#279]
We should start using SSR instead of generating a static site. This will require using the data loading APIs that Next.js offers instead of reading directly from the `data.json` file.

**Comment by lucavallin** [comment]
@dnafication You might be interested!

**Comment by dnafication** [comment]
Thanks for considering @lucavallin, feel free to assign it to me. 😊

**Comment by lucavallin** [comment]
@dnafication I did some refactoring tonight, the scope changed a bit. But the SSR part is still valid!
