### ISSUE TITLE
Linkedin link broken.

### ISSUE THREAD

**Issue by ivanosquis10** [lucavallin/verto#286]
![image](https://github.com/lucavallin/verto/assets/83567373/7a1a92df-66d2-469e-b167-6a3a8ff8d001)

This is the information from the linkedin link, which leads to a profile that "does not exist".
![image](https://github.com/lucavallin/verto/assets/83567373/835d9769-0336-40e0-b215-dba2720d469b)

And this link takes me to the correct profile
Link: https://www.linkedin.com/in/lucavallin/

**Comment by lucavallin** [comment]
Good catch, fixed!
