### ISSUE TITLE
Suggestion: add tag for documentation needs

### ISSUE THREAD

**Issue by MattDemers** [lucavallin/verto#287]
I'm not much of a coder, but I'd like to contribute to Github projects in a way I know how: editing and expanding documentation, and making sure language is clear, concise, reading well, etc.

I like the idea of this project, just figure I'd throw my hat in in terms of expansion towards non-coders.

**Comment by lucavallin** [comment]
Hey @MattDemers, great idea. Unfortunately, the tags we show come directly from GitHub at this time. Therefore, `documentation` is a tag a repo should have, for us to display it.

**Comment by Dhruvabhat24** [comment]
Can you please provide some more information about the issue

**Comment by MattDemers** [comment]
> Can you please provide some more information about the issue

I think it's safe to close this, tbh. Thanks @lucavallin/
