### ISSUE TITLE
Let users register

### ISSUE THREAD

**Issue by lucavallin** [lucavallin/verto#290]
The project is currently a static site which limits the possible features quite a bit. It would be great to make it possible for users to register, as a first step towards adding new features.

Related to https://github.com/lucavallin/verto/issues/289.

**Comment by ATLAS2002** [comment]
I would like to work on this issue @lucavallin

**Comment by ArindamPal-0** [comment]
@lucavallin Why is there a need for user registration, what features are you thinking for registered users?

**Comment by lucavallin** [comment]
@ArindamPal-0 For example, users could save repositories to have a "favourite" list, and other such features.

**Comment by ATLAS2002** [comment]
Hi there @lucavallin , I have just created a pull request regarding this issue, you can find it here #319 . I have setup a authentication service also refactored and updated existing code for better compatibility with this feature. Please let me know if there is anything that needs to be worked on.
