### ISSUE TITLE
Fix favicons

### ISSUE THREAD

**Issue by lucavallin** [lucavallin/verto#291]
For some reason, Google does not show the project's favicon in the search results. They are possibly not configured correctly. I did look into the issue, but I didn't have much time to really figure out what Google wants from us.

**Comment by 123MwanjeMike** [comment]
Hi @lucavallin, I noticed that changes to effect this were made a few days back in [this commit](https://github.com/123MwanjeMike/verto/commit/097d1c95731e68a5b20cc622b085f450596f836e) according to the [Google search docs](https://developers.google.com/search/docs/appearance/favicon-in-search) and are already on the website.
![image](https://github.com/lucavallin/verto/assets/41787587/195ff7a0-741a-4ac6-92b0-780cc7dc92a3).

The documentation also states that the changes may take a couple of days to reflect to reflect I guess we can give it sometime
![image](https://github.com/lucavallin/verto/assets/41787587/7ee55926-cfc2-4b31-87af-423de5ede063)

**Comment by josephbartley** [comment]
works on my machine :tada: 

![image](https://github.com/lucavallin/verto/assets/16933164/1ef36efa-fa9a-4f7f-8706-2b9d6e29a1ec)

**Comment by lucavallin** [comment]
@josephbartley Your comment fixed the issue, thanks!
