### ISSUE TITLE
Search repos by multiple tags

### ISSUE THREAD

**Issue by ATLAS2002** [lucavallin/verto#293]
As of now we can only search projects based on one tag. Now if people can search with **more than one tags**, that would be really cool.
This feature can further be improved by allowing users to choose between **broader** and **precise** searching options. Imo that would greatly **enhance the UX**.

**Comment by ATLAS2002** [comment]
@lucavallin can you assign this issue to me?

**Comment by ArindamPal-0** [comment]
This issue was already raised earlier #212

**Comment by ATLAS2002** [comment]
> > As of now we can only search projects based on one tag. Now if people can search with **more than one tags**, that would be really cool. This feature can further be improved by allowing users to choose between **broader** and **precise** searching options. Imo that would greatly **enhance the UX**.
> 
> This issue was already raised earlier in #212
> 
> I'm working on the issue, if you have any suggestions feel free to start a conversation there.

Oh my bad, didn't notice. But I'm also curious to know if the same issue will be reworked on once the app starts using a database to get all the info

**Comment by ArindamPal-0** [comment]
> > > As of now we can only search projects based on one tag. Now if people can search with **more than one tags**, that would be really cool. This feature can further be improved by allowing users to choose between **broader** and **precise** searching options. Imo that would greatly **enhance the UX**.
> > 
> > 
> > This issue was already raised earlier in #212
> > I'm working on the issue, if you have any suggestions feel free to start a conversation there.
> 
> Oh my bad, didn't notice. But I'm also curious to know if the same issue will be reworked on once the app starts using a database to get all the info

Oh, I was not aware of talks about the site moving from static to SSR. I think if the site is moving to SSR, then some more discussion on issue #212 will be needed before implementing the multiple tags feature. I think rework can be avoided altogether, cause I've just started to implement the feature.
