### ISSUE TITLE
Add button to sort repositories by new issues

### ISSUE THREAD

**Issue by lucavallin** [lucavallin/verto#32]
We are missing a button in the list of repositories on the website to sort by stars, last updated and by new issues. The data is already available, but the sort button and functionality are not.

**Comment by thebarshablog** [comment]
Will check it out!

**Comment by tamiresviegas** [comment]
I will try to solve this issue

**Comment by lucavallin** [comment]
Sort by stars and the architecture needed for that and future sorting has already been address in https://github.com/lucavallin/first-issue/pull/112 by @isaacwashere .

**Comment by isaacwashere** [comment]
@lucavallin WOAH I did not see that bug when working on this locally, and I made sure to do weird toggles between the 2 star buttons. 

I have a hunch that it could be the slicing that's happening in the `RepositoryList` but tbh I'm not sure how to repro this locally. I'll see if maybe I can do a prod-level GitHub query 🤔 Maybe I need more data. But yea, this is weird, and I'll try to look into it today 👍

**Comment by isaacwashere** [comment]
I've put up a PR for that bug https://github.com/lucavallin/first-issue/pull/114 👍

**Comment by nrhitik** [comment]
I would like to work on this issue. please assign me this issue.

**Comment by lucavallin** [comment]
@nrhitik Thanks for your interest. Please go ahead ;)

**Comment by iaminebriki** [comment]
@lucavallin 
As of now there is a sort by stars (most, least) in two separate buttons, I thought It would useful to make it as **_one "Sort by stars"_** button that **change order (ascendant, descendant) every click**. 
Another Sort by button that would be useful to check which repos are maintained is the **Sort by Activity also in two different oreders** so we can sort repos by last activity.

**Comment by JacobRosey** [comment]
Opened a PR for this issue
